from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
import django.utils.timezone
class Migration(migrations.Migration):
 initial=True
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name="Institution",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(default="CampusConnect Academy",max_length=180)),("tagline",models.CharField(default="Everything your campus needs to communicate better",max_length=220)),("logo",models.ImageField(blank=True,null=True,upload_to="institution/")),("address",models.TextField(blank=True)),("phone",models.CharField(blank=True,max_length=30)),("email",models.EmailField(blank=True,max_length=254)),("primary_color",models.CharField(default="#3157f6",max_length=20))]),
 migrations.CreateModel(name="Department",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120,unique=True)),("short_name",models.CharField(blank=True,max_length=20))],options={"ordering":["name"]}),
 migrations.CreateModel(name="Category",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=100,unique=True)),("icon",models.CharField(default="📢",max_length=10)),("color",models.CharField(default="#3157f6",max_length=20))],options={"ordering":["name"]}),
 migrations.CreateModel(name="Notice",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=200)),("content",models.TextField()),("audience",models.CharField(choices=[("all","Everyone"),("students","Students"),("staff","Staff"),("parents","Parents")],default="all",max_length=20)),("priority",models.CharField(choices=[("low","Low"),("normal","Normal"),("high","High"),("urgent","Urgent")],default="normal",max_length=10)),("image",models.ImageField(blank=True,null=True,upload_to="notices/images/")),("attachment",models.FileField(blank=True,null=True,upload_to="notices/files/")),("is_published",models.BooleanField(default=True)),("is_pinned",models.BooleanField(default=False)),("publish_date",models.DateTimeField(default=django.utils.timezone.now)),("expiry_date",models.DateTimeField(blank=True,null=True)),("views",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("author",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL)),("category",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notices",to="notices.category")),("department",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notices",to="notices.department"))],options={"ordering":["-is_pinned","-publish_date"]})]
